"""
LangGraph node functions.

Graph flow:
    parse_shipment
        ↓
    orchestrate_risk   ←─── (loops via ToolNode until all tools done)
        ↓
    generate_report
        ↓
    END
"""
from __future__ import annotations

import json
import logging
from typing import Any

from langchain_core.messages import AIMessage, HumanMessage, SystemMessage, ToolMessage
from langchain_openai import ChatOpenAI

from .state import TransportRiskState, RiskScore, ShipmentDetails, default_state, risk_level
from .tools import ALL_TOOLS

logger = logging.getLogger(__name__)

# ---------------------------------------------------------------------------
# LLM setup — bind all tools for function-calling
# ---------------------------------------------------------------------------

def _build_llm() -> ChatOpenAI:
    return ChatOpenAI(
        model="gpt-4o",
        temperature=0.1,
        streaming=False,
    ).bind_tools(ALL_TOOLS)


_PARSE_SYSTEM = """
You are a transport risk data-extraction assistant.

Your ONLY job is to extract structured shipment information from the user's message
and return it as a JSON object with these exact keys:

{
  "shipment_id": "string or empty",
  "origin": "string",
  "destination": "string",
  "carrier": "string or empty",
  "cargo_type": "string or empty",
  "departure_date": "YYYY-MM-DD or empty",
  "route_waypoints": ["list", "of", "strings"],
  "weight_kg": number or 0,
  "value_usd": number or 0
}

Return ONLY the JSON object. No markdown, no explanation.
"""

_ORCHESTRATOR_SYSTEM = """
You are a transport risk assessment agent.

Your task is to evaluate shipment risk across FOUR dimensions by calling ALL
four tools in order:

1. check_route_disruption    — detect route disruptions / chokepoints
2. predict_delay             — predict delay probability
3. assess_weather_geopolitical_risk — weather + geopolitical scoring
4. score_carrier_performance — evaluate the carrier

Use the shipment details provided. Call each tool ONCE. After all four tool
calls are complete, reply with the single word: DONE
"""

_REPORT_SYSTEM = """
You are a senior transport risk analyst.

Write a professional risk report in Markdown from the structured risk data
provided. Structure it exactly as:

# Transport Risk Report — {shipment_id}

## Executive Summary
One paragraph, overall risk level, headline finding.

## Shipment Details
Table with: Origin, Destination, Carrier, Cargo Type, Departure, Weight, Value.

## Risk Scorecard
| Dimension | Score | Level | Key Finding |
(all four rows)

## Detailed Findings

### Route Disruption
(evidence bullets + recommendations)

### Delay Prediction
(estimated delay range + evidence + recommendations)

### Weather & Geopolitical
(weather sub-score, geo sub-score, evidence, recommendations)

### Carrier Performance
(KPI table if available + evidence + recommendations)

## Overall Risk: {level}

## Priority Actions
Numbered list of top 5 actions the logistics team should take NOW.

---
*Report generated by Transport Risk Agent | Powered by GPT-4o + LangGraph*

Use professional language. Be specific and actionable.
"""

# ---------------------------------------------------------------------------
# Node: parse_shipment
# ---------------------------------------------------------------------------

async def parse_shipment(state: dict) -> dict:
    """
    Extract structured ShipmentDetails from the latest human message.
    Uses a small LLM call (no tools) for reliable JSON extraction.
    """
    llm = ChatOpenAI(model="gpt-4o", temperature=0)

    # Grab the latest human text
    user_text = ""
    for msg in reversed(state.get("messages", [])):
        if isinstance(msg, HumanMessage):
            user_text = msg.content
            break

    if not user_text:
        return {"error": "No user message found to parse"}

    response = await llm.ainvoke([
        SystemMessage(content=_PARSE_SYSTEM),
        HumanMessage(content=user_text),
    ])

    try:
        raw = response.content.strip()
        # Strip markdown fences if present
        if raw.startswith("```"):
            raw = raw.split("```")[1]
            if raw.startswith("json"):
                raw = raw[4:]
        data = json.loads(raw)
        shipment = ShipmentDetails(
            shipment_id=data.get("shipment_id", "SHP-UNKNOWN"),
            origin=data.get("origin", ""),
            destination=data.get("destination", ""),
            carrier=data.get("carrier", "unknown"),
            cargo_type=data.get("cargo_type", "general"),
            departure_date=data.get("departure_date", ""),
            route_waypoints=data.get("route_waypoints", []),
            weight_kg=float(data.get("weight_kg", 0)),
            value_usd=float(data.get("value_usd", 0)),
        )
    except (json.JSONDecodeError, KeyError, ValueError) as exc:
        logger.warning("parse_shipment JSON error: %s", exc)
        # Fallback: put raw text into a minimal shipment
        shipment = ShipmentDetails(
            shipment_id="SHP-UNKNOWN",
            origin=user_text[:40],
            destination="",
        )

    return {"shipment": shipment}


# ---------------------------------------------------------------------------
# Node: orchestrate_risk   (the ReAct loop — calls tools)
# ---------------------------------------------------------------------------

async def orchestrate_risk(state: dict) -> dict:
    """
    ReAct-style orchestrator that calls the four risk tools.
    LangGraph's ToolNode handles the actual tool execution; this node
    builds/updates the message list for the LLM.
    """
    llm = _build_llm()
    shipment: ShipmentDetails = state.get("shipment", ShipmentDetails())

    # Build the system + context message
    context = (
        f"Shipment details:\n"
        f"- ID: {shipment.shipment_id}\n"
        f"- Origin: {shipment.origin}\n"
        f"- Destination: {shipment.destination}\n"
        f"- Carrier: {shipment.carrier}\n"
        f"- Cargo type: {shipment.cargo_type}\n"
        f"- Departure date: {shipment.departure_date}\n"
        f"- Waypoints: {', '.join(shipment.route_waypoints) or 'none'}\n"
        f"- Weight: {shipment.weight_kg} kg\n"
        f"- Value: ${shipment.value_usd:,.0f}\n"
    )

    messages = state.get("messages", [])

    # On first entry, inject orchestrator system prompt
    has_system = any(isinstance(m, SystemMessage) for m in messages)
    if not has_system:
        messages = [
            SystemMessage(content=_ORCHESTRATOR_SYSTEM),
            HumanMessage(content=context),
            *messages,
        ]

    response = await llm.ainvoke(messages)
    return {"messages": [response]}


# ---------------------------------------------------------------------------
# Node: process_tool_results
# ---------------------------------------------------------------------------

def process_tool_results(state: dict) -> dict:
    """
    Scan ToolMessage results in the message list, parse JSON payloads,
    and write them into typed RiskScore fields on the state.
    """
    updates: dict[str, Any] = {}

    for msg in state.get("messages", []):
        if not isinstance(msg, ToolMessage):
            continue
        try:
            data = json.loads(msg.content)
        except (json.JSONDecodeError, TypeError):
            continue

        tool_name = data.get("tool", "")
        score = RiskScore(
            score=data.get("score", 0.0),
            level=data.get("level", "unknown"),
            summary=data.get("summary", ""),
            evidence=data.get("evidence", []),
            recommendations=data.get("recommendations", []),
        )

        if tool_name == "route_disruption":
            updates["route_risk"] = score
        elif tool_name == "delay_prediction":
            updates["delay_risk"] = score
        elif tool_name == "weather_geopolitical":
            updates["weather_geo_risk"] = score
        elif tool_name == "carrier_performance":
            updates["carrier_risk"] = score

    # Compute aggregate if we have at least one score
    scores = []
    weights = []
    for key, weight in [
        ("route_risk", 0.30),
        ("delay_risk", 0.25),
        ("weather_geo_risk", 0.25),
        ("carrier_risk", 0.20),
    ]:
        risk: RiskScore = updates.get(key) or state.get(key, RiskScore())
        if risk.score > 0:
            scores.append(risk.score * weight)
            weights.append(weight)

    if scores:
        overall = sum(scores) / sum(weights) if weights else 0.0
        updates["overall_risk_score"] = round(overall, 3)
        updates["overall_risk_level"] = risk_level(overall)

    return updates


# ---------------------------------------------------------------------------
# Node: generate_report
# ---------------------------------------------------------------------------

async def generate_report(state: dict) -> dict:
    """
    Ask GPT-4o to write a polished Markdown risk report from the collected
    risk scores and shipment details.
    """
    llm = ChatOpenAI(model="gpt-4o", temperature=0.2)

    shipment: ShipmentDetails = state.get("shipment", ShipmentDetails())
    route_risk: RiskScore = state.get("route_risk", RiskScore())
    delay_risk: RiskScore = state.get("delay_risk", RiskScore())
    wg_risk: RiskScore = state.get("weather_geo_risk", RiskScore())
    carrier_risk: RiskScore = state.get("carrier_risk", RiskScore())
    overall_score = state.get("overall_risk_score", 0.0)
    overall_level = state.get("overall_risk_level", "unknown")

    payload = {
        "shipment": {
            "id": shipment.shipment_id,
            "origin": shipment.origin,
            "destination": shipment.destination,
            "carrier": shipment.carrier,
            "cargo_type": shipment.cargo_type,
            "departure_date": shipment.departure_date,
            "weight_kg": shipment.weight_kg,
            "value_usd": shipment.value_usd,
            "waypoints": shipment.route_waypoints,
        },
        "overall": {"score": overall_score, "level": overall_level},
        "route_disruption": {
            "score": route_risk.score, "level": route_risk.level,
            "summary": route_risk.summary,
            "evidence": route_risk.evidence,
            "recommendations": route_risk.recommendations,
        },
        "delay_prediction": {
            "score": delay_risk.score, "level": delay_risk.level,
            "summary": delay_risk.summary,
            "evidence": delay_risk.evidence,
            "recommendations": delay_risk.recommendations,
        },
        "weather_geopolitical": {
            "score": wg_risk.score, "level": wg_risk.level,
            "summary": wg_risk.summary,
            "evidence": wg_risk.evidence,
            "recommendations": wg_risk.recommendations,
        },
        "carrier_performance": {
            "score": carrier_risk.score, "level": carrier_risk.level,
            "summary": carrier_risk.summary,
            "evidence": carrier_risk.evidence,
            "recommendations": carrier_risk.recommendations,
        },
    }

    system = _REPORT_SYSTEM.replace(
        "{shipment_id}", shipment.shipment_id
    ).replace(
        "{level}", overall_level.upper()
    )

    response = await llm.ainvoke([
        SystemMessage(content=system),
        HumanMessage(content=json.dumps(payload, indent=2)),
    ])

    return {"final_report": response.content}


# ---------------------------------------------------------------------------
# Edge condition: should_continue
# ---------------------------------------------------------------------------

def should_continue(state: dict) -> str:
    """
    Routing function for the orchestrate_risk node.

    - If the last AI message has tool_calls → route to 'tools' (ToolNode)
    - If the last AI message says 'DONE' or has no tool calls → route to
      'process_results'
    """
    messages = state.get("messages", [])
    last = messages[-1] if messages else None

    if isinstance(last, AIMessage):
        if last.tool_calls:
            return "tools"
        content = (last.content or "").strip().upper()
        if "DONE" in content or not last.tool_calls:
            return "process_results"

    return "process_results"
